@baseUrl = http://localhost:3001/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM4NTU1NjAsImlkX3VzZXIiOiJabWMtWGYtbiJ9.yKQm75sBj0k6nY2GJjORaOpmcRgzRYcWWK9uE0BzMDU

# Register Success
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Ardi",
  "email": "ardi@example.com",
  "password": "password123",
  "confirm_password": "password123"
}

###

# Register Fail [Email is invalid]
POST {{baseUrl}}/auth/register
Content-Type: application/json 

{
  "name": "Ardi",
  "email": "Bad Email",
  "password": "123456",
  "confirm_password": "123456"
}

###

# Register Fail [Password is not match]
POST {{baseUrl}}/auth/register
Content-Type: application/json 

{
  "name": "Ardi",
  "email": "ardi@example.com",
  "password": "123450",
  "confirm_password": "123456"
}

###

# Register Fail [Input required]
POST {{baseUrl}}/auth/register
Content-Type: application/json 

{
  "name": "",
  "email": "",
  "password": "",
  "confirm_password": ""
}

###

# Login success
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ardi@example.com",
  "password": "password123"
}

###

# Login Fail [Email is invalid]
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "Bad email",
  "password": "password123"
}

###

# Login Fail [Input required]
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

# Check Auth
GET {{baseUrl}}/auth
Content-Type: application/json
Authorization: {{token}}