@baseUrl = http://localhost:3001/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM3ODg5OTUsImlkX3VzZXIiOiJabWMtWGYtbiJ9.ZUsw_94izA3Dr8LQxS7BXOpRKzjZw7b3am5KYS9qTeg

# Login success
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ardi@example.com",
  "password": "password123"
}

###

# Invitation Success
POST {{baseUrl}}/invitation/create
Content-Type: application/json
Authorization: {{token}}

{
  "id_template": "UNDANGN1",
  "title": "Test",
  "date": "2025-08-01",
  "time": "15:10:00",
  "location": "Test",
  "description": "Test",
  "primary_color": "Test",
  "secondary_color": "Test",
  "background_image": "wedding_1.jpg"
}

###

# Invitation Fail [Input Required]
POST {{baseUrl}}/invitation/create
Content-Type: application/json
Authorization: {{token}}

{
  "id_template": "",
  "title": "",
  "date": "",
  "time": "",
  "location": "",
  "description": "",
  "primary_color": "",
  "secondary_color": ""
}

###

# Get Invitations
GET {{baseUrl}}/invitation
Content-Type: application/json
Authorization: {{token}}

###

# Generate Link Success
POST {{baseUrl}}/invitation/generate_link
Content-Type: application/json
Authorization: {{token}}

{
  "id_invitation": "ayvBVfF0"
}

###

# Generate Link Fail
POST {{baseUrl}}/invitation/generate_link
Content-Type: application/json
Authorization: {{token}}

{
  "id_invitation": "ayvBfF0"
}

###

# Share social media suuccess
POST {{baseUrl}}/invitation/share_social_media
Content-Type: application/json
Authorization: {{token}}

{
  "id_invitation": "ayvBVfF0",
  "name_platform": "whatsapp"
}